### ISSUE TITLE
requirements.txt file

### ISSUE THREAD

**Issue by cleesmith** [miklevin/Pipulate.com#2]
avoid this project!!!

**Comment by miklevin** [comment]
Okay, done. But pip itself isn't installed (long story). I'm using easy_install instead, which is in the Tiny Core Linux repository. I will change this as soon as Python 3.x reaches the Tiny Core repository, and switch the installs over from easy_install to pip. In the meanwhile, I can still provide this requirements.txt file by way of documentation (and you can always easy_install pip -- but if you'll try, you see why I don't do it this way).

**Comment by miklevin** [comment]
Yeah, totally allowed! Pipulate can be completely separate from Levinux and Tiny Core Linux for that matter. But I'm working on both and need to get the efficiency of them working together. 

A lot of interest in Levinux is the lack-of-installer and the lack-of-need for admin rights on the machine you're working on. It's one of the truly floating tiny versions of Linux out there, and a lot of people are looking for this. I get about 20 downloads/day based on mostly just that.

And so as much as I tried to get off of Tiny Core Linux so I could use all the freedoms of say a Debian or Red Hat based Linux with an awesome repository, a dozen tiny reasons keep pulling be back to Tiny Core. It really is a unique distro that helps with apps like this. And as such, I'm stuck with the software in their repository—I'm not actually up to creating new extensions for TCL and submitting them to the repository. I'm just waiting for others to do that. And they have 2 huge omissions in the repository: Python 3.x and pip! They do have 2.7 and Distribute (easy_install).

I have every intention of switching to 3.x and pip the second they hit the TCL repository. But until they do, I have to do it this way. Yes, there are work-arounds, but I'm already going against the grain enough. If I'm going to live in the fringe, I need to live in the supported areas of the fringe.

Have faith that I will modernize in lock-step with Tiny Core Linux itself.

**Comment by miklevin** [comment]
Hmmmm. Another part of the answer is that I'll be teaching everyone how to make a Unix-like, Python, vim and git development and code execution environment pretty much anywhere. With or without Docker. Right on your Windows machine (MinGW) or on your Mac (already there), or a Raspberry Pi or whatever hardware you have, so long as it can run Python and have Web access.

I'm breaking the messages that I have to deliver into separate chunks for separate audiences. The Levinux/Pipulate combo is designed to work as a gateway drug for several of these audiences, and then route them off to separate websites/approaches/initiatives suited to them.

I really love that Pipulate can run on almost anything. Sometimes I think of Levinux as turning a virtual computer into a meme that can spread like silly cat videos.

**Comment by miklevin** [comment]
Yeah, Levinux is about playing a sort of Pied Piper game with open minded millennials and digital natives, enticing them into new things, and perchance forming new or supplemental habits. I'm actually trying to form it into a sort of game.  

And as the game goes, I will spin them off to other things, like real server hardware or robots. Or native code on their laptops. All the while, Python, vim and git are the themes that run through it—tech tools on which you can actually achieve mastery and rely on always being there to help fight disruption.

A vitamin supplement to whatever other tech is in your diet. Stop me before I mix in even more metaphors.

**Comment by miklevin** [comment]
Fantastic! I forgot the oauth2 gotcha if you're not simulating localhost with port forwarding. There are solutions but they are convoluted. My real solution will be offering an old fashioned username and password field for those who are stuck in a hosting context that is neither localhost nor a registered domain. Not as secure, but pragmatic. 

Thanks for all the info from this experience!

**Comment by miklevin** [comment]
I'm definitely liking this. I backup all site-packages  directory as my solution; but I'd rather install onto the /home persistent drive and avoid backups and restores. So I go from distribute from TCL repository to easy_install virtualenv then use pip for everything else. Interesting. Thanks. I look forward to testing it out.

**Comment by cleesmith** [comment]
Do you have a suggestion as to how large to make the drive img for home ?
... or does it grow, say, as users add projects/work
... I'm using a qcow2 img of 8GB, which is probably too big as I don't really see doing development on 
qemu/core as it's, well, pokey ... but I can see git cloning and installing/testing on qemu/core

Also, some python packages actually want to use gcc/tools to install faster native code ... is there an equivalent to the usual `build-essential` (ubuntu/debian) for core ?  if you know
... I think I saw `compiletc` mentioned somewhere
Nevermind, `tce-load -wi compiletc` was the solution.

**Comment by miklevin** [comment]
It grows so you can err on the size of large. I only did 1GB per on the spirit of staying small, but I may remaster the home drive to allow inflation to 5GB or so.

**Comment by miklevin** [comment]
Also don't worry about using the Levinux approach for everything. I'm advocating Levinux as a sort of lifeboat from other environments. That's why I am so in favor of Pipulate running on anything that supports Python. Get a few tricks down on Levinux then move onto less pokey platforms.

**Comment by miklevin** [comment]
Your input is clever and very appreciated. If done well, I think Levinux could trigger a sort of following by people looking for something more... well, core. And Pipulate, once I evolve it a bit (scheduling, crawling, etc.) Could have its own sort of following. You provide some validation that it is actually interesting stuff.

**Comment by miklevin** [comment]
Pipulate is designed to make programming more immediately useful to anyone needing to do a bunch of lookups regularly against a data source. It's easy enough to write a single function to do one lookup but it's another matter to put it in a loop and parameterize it and have it at your fingertips as a general and expandable tool. SEO and Social Media are just the no-brainer applications. There are countless others. 

Good luck on the Yosemite upgrade.

**Comment by miklevin** [comment]
They'll be broken out for sure. I'll import them with the same name space as the parent file so I don't have to accommodate for dot this and dot that in the function names in the spreadsheet column headers. But the functions conceivably could pull in from other files, google docs or wherever. Yes, it's a hacking vulnerability when carried too far. But hey, on Levinux or Docker, you can just hit reset.

**Comment by miklevin** [comment]
from module.py import *

**Comment by miklevin** [comment]
It wasn't done. I was just explaining what it would be. I just did it in the main repsitory. I went with functions.py, and the import doesn't use the .py extension. Tested and works.

**Comment by miklevin** [comment]
No, I hate all the design decisions since IOS 7. Jony Ives may be great with hardware designs, but his war against Steve Job's skeuomorphic approach to software has been a disaster. That old comfortable feeling of being at home in your tools is gone, and it feels instead like Ikea took over the Mac and iPhone.
